### ISSUE TITLE
Many to many relationship stores term as 'taxonomy::term'

### ISSUE THREAD

**Issue by mikemartin** [Stillat/relationships#21]
When using the relationship below, the taxonomy term is stored with the taxomony name causing a new taxonomy term to be created.

```
activities:
  - 'activities::drawing'
  - 'activities::drafting'
```

### Relation
```
Relate::manyToMany(
            'term:activities.products',
            'pens.activities'
        );
```

Activities term `products` field:
```
-
            handle: products
            field:
              mode: default
              create: true
              collections:
                - pens
                - markers
                - refills
                - accessories
              display: Products
              type: entries
              icon: entries
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
```

Pen entry `activities` field:
```
-
            handle: activities
            field:
              type: terms
              taxonomies:
                - activities
              display: Activities
              mode: select
```
