### ISSUE TITLE
Sync issue with update and delete

### ISSUE THREAD

**Issue by andrewhtolle** [Stillat/relationships#30]
Hi,

I made the following relationship and when I create everything works fine. The problem his that when I update or delete the relationship its not shared/updated with the other entry.

```
Relate::oneToMany(
  'employees.related_office',
  'offices.related_employees'
);
```

employees.yml
```
handle: related_office
field:
  max_items: 1
  mode: default
  create: true
  collections:
    - offices
  display: Office
  type: entries
  icon: entries
  listable: hidden
  instructions_position: above
  read_only: false
```

offices.yml
```
handle: related_employees
field:
  mode: default
  create: true
  collections:
    - employees
  display: Employés
  type: entries
  icon: entries
  listable: hidden
  instructions_position: above
  read_only: false
```
