### ISSUE TITLE
Taxonomy term manyToMany relationship

### ISSUE THREAD

**Issue by mikemartin** [Stillat/relationships#33]
Hey @JohnathonKoster 

I’ve tried creating a manyToMany relationship between 2 taxonomy term fields. It seems to be picked up in the relate:list command, but doesn’t run with the relate:fill command. 

Thanks!

**Comment by JohnathonKoster** [comment]
Thanks for the report! Are you running the latest versions of Statamic, and flat-file vs. Eloquent? I'll take a look later on this weekend; if I have any troubles reproducing I'll let you know! 🙂

**Comment by mikemartin** [comment]
Latest version and flat file.

**Comment by mikemartin** [comment]
Hey @JohnathonKoster 
Here's some more details.

```
Relate::manyToMany(
          'term:colours.colour_groups',
          'term:colour_groups:colours'
);
```

**Relate list output**
```
+---+--------------------+----------------------+----------------------+---------------+--------------------+--------------+----------------+-----------------------+
|   | Primary Collection | Related Collection   | Primary Field        | Related Field | Relationship       | With Events? | Allow Deletes? | Is Automatic Inverse? |
+---+--------------------+----------------------+----------------------+---------------+--------------------+--------------+----------------+-----------------------+
| 1 | [term].[term]      | [term].colour_groups | [term].colour_groups | colours       | Many to Many (*-*) | No           | Yes            | No                    |
| 2 | [term].[term]      | [term].colours       | [term].colours       | colour_groups | Many to Many (*-*) | No           | Yes            | Yes (1)               |
+---+--------------------+----------------------+----------------------+---------------+--------------------+--------------+----------------+-----------------------+
```


Colours taxonomy - colour_groups field
```
-
  handle: colour_groups
  field:
    mode: select
    create: false
    taxonomies:
      - colour_groups
    type: terms
    display: Colour Groups
    listable: true
    instructions_position: above
    visibility: visible
    replicator_preview: true
    hide_display: false

```

Colour Groups taxonomy - colours field
```
-
  handle: colours
  field:
    mode: default
    create: false
    taxonomies:
      - colours
    type: terms
    display: Colours
    listable: true
    instructions_position: above
    visibility: visible
    replicator_preview: true
    hide_display: false
```


**Support details**
```
Environment
Application Name: Pilot Pen Australia
Laravel Version: 10.48.3
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: pilot.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Locales
Installed
Locales Version: 1.9.0
Protected

Localization
Installed: en
LaravelLang\Attributes\Plugin: 2.9.4
LaravelLang\HttpStatuses\Plugin: 3.8.2
LaravelLang\Lang\Plugin: 13.12.0
Protected Locales: en
Publisher Version: 14.7.1

Statamic
Addons: 15
Antlers: runtime
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.53.2 PRO

Statamic Addons
aerni/social-links: 3.1.0
aniket-magadum/insta-feeds: 1.0.1
duncanmcclean/static-cache-manager: 3.1.2
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-livewire: 2.12.0
mikemartin/helpscout-beacon: 1.0.3
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-color-swatches: 2.2.0
steadfastcollective/statamic-csv-exporter: 2.2.1
stillat/relationships: 2.1.4
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 8.3.0
studio1902/statamic-peak-tools: 4.4.2
swiftmade/statamic-clear-assets: 2.0.1
```
