### ISSUE TITLE
OneToMany not syncing with Eloquent Driver

### ISSUE THREAD

**Issue by swen4** [Stillat/relationships#43]
I cannot seem to get my collectons to sync using a OneToMany relationship. I'm using eloquent driver with the following setup:

- Entries are in database
- Blueprints are in files

My two collections are as follows:
- Collection handle: articles -> revisions enabled
- Collection handle: quotes

I'm trying to set up the following relationship:
```
public function boot(): void
{
    /**
     * Entry relationships between articles and quotes
     */
    Relate::OneToMany(
        'quotes.article',
        'articles.quotes'
    );
}
```

- Quotes can be linked to an article
- An article can have many quotes

My blueprints have the following fields:

### article.yaml
```
-
  handle: quotes
  field:
    mode: default
    create: true
    collections:
      - quotes
    display: Quotes
    type: entries
    listable: true
```

### quote.yaml
```
-
  handle: article
  field:
    max_items: 1
    type: entries
    mode: default
    collections:
      - articles
    display: Artikel
    listable: true
```

### Output of php please relate:list
```
+---+--------------------+--------------------+------------------+---------------+-------------------+--------------+----------------+-----------------------+
|   | Primary Collection | Related Collection | Primary Field    | Related Field | Relationship      | With Events? | Allow Deletes? | Is Automatic Inverse? |
+---+--------------------+--------------------+------------------+---------------+-------------------+--------------+----------------+-----------------------+
| 1 | [entry].quotes     | [entry].article    | [entry].articles | quotes        | Many to One (*-1) | Yes          | Yes            | No                    |
| 2 | [entry].articles   | [entry].quotes     | [entry].quotes   | article       | One to Many (1-*) | Yes          | Yes            | Yes (1)               |
+---+--------------------+--------------------+------------------+---------------+-------------------+--------------+----------------+-----------------------+
```

Some observations:

- In the output of relate:list, it looks like the values for "related collection", "primary field" and "related field" might be wrong, using singular/plural incorrectly.
- The synchronization doesn't happen either way. Adding a quote to an article doesn't sync, and adding an article to a quote doesn't sync
- The output of php please relate:fill shows:

```
Updating relationships. This may take a while if you have a lot of entries.

Updating relationship: (1-*) [articles.quotes quotes.article]...
Updating relationship: (1-*) [articles.quotes quotes.article]... done!
```

Is there a misconfiguration on my part, or is there a potential bug at play?
