### ISSUE TITLE
Q: Multiple collections related to multiple other collections

### ISSUE THREAD

**Issue by jacksleight** [Stillat/relationships#8]
Hey John, thanks for this awesome addon, I _think_ it's exactly what I need, I just can't quite figure out the right way to configure it for my situation. Hope you might be able to give me some advise.

I'm working on a site that has five collections, and any of the entries in these collections could be related to any of the entries in any of the other collections. All the blueprints have the same `related` entries field:

```yaml
handle: related
field:
  mode: default
  create: false
  collections:
    - events
    - clubs
    - businesses
    - services
    - articles
  display: Related
  type: entries
  icon: entries
  listable: hidden
  instructions_position: above
  read_only: false
```

What I'd like to happen is that when you add an entry to one of these fields the inverse relationship is also created.

As a start I tried to just add one relationship:

```php
Relate::manyToMany(
    'articles.related',
    'services.related'
);
```

But I get an error when I run `relate:fill`.

Not sure if I'm setting up the relationship wrong, or I need to configure my fields differently, or if this kind of relationship just isn't possible? Thanks!
